# Futures, aproximación

Esto se va poniendo cada vez más lindo porque desde este artículo, vamos a ver
lo último necesario para poder empezar a crear aplicaciones que interactúen con
el mundo exterior a nuestra computadora.

Como ya conocen por experiencia propia, el interactuar con otros, requiere de
tiempo: alguien habla, el otro espera y escucha. Con nuestras aplicaciones
sucede lo mismo: pedimos un dato a un servidor en algún lugar de internet y
mientras esperamos. Sin embargo, imagínense si mientras un dato está viniendo
hacia nuestra aplicación, no pudiéramos hacer nada!

Van a existir caso para los cuales tendremos que esperar sí o sí y si el
resultado de esta operación no sucede en el tiempo que estimamos debería haber
sucedido, podremos mostrar un mensaje al usuario y volver a intentarlo. Van a
existir otros casos en los que podremos enviar un pedido y mientras este recorre
ceros y unos por algún lugar del universo, haremos otras cosas.

__Todos estos procesos de espera y el mientras tanto, reciben el nombre de asincronía.__

Las operaciones asíncronas son aquellas que no bloquean la ejecución
del programa y permiten que otros procesos se ejecuten mientras esperan la
finalización de la operación en cuestión. Estas operaciones se utilizan para
realizar tareas que pueden llevar un tiempo prolongado, como la descarga de
datos de Internet o la ejecución de operaciones de E/S (Entrada/Salida) en
archivos.

Para comenzar con estas operaciones asíncronas, Dart nos proporciona el concepto
de Futuros.

## Futures

Un _Future_ es __un objeto que representa el resultado potencial de una
operación asíncrona.__ Cuando se crea un _Future_, se inicia una tarea en segundo
plano que realizará la operación asíncrona y devolverá un valor al _Future_ cuando
la tarea haya finalizado. Mientras tanto, la ejecución del programa puede
continuar sin bloquearse. Para trabajar con Futuros se utilizan una serie de métodos y
operaciones que vamos a ver de a poco!

Supongamos que vamos a simular una aplicación de un restaurant que nos dice,
dado un número de comensales, si tiene disponibilidad o no en el momento. Para
ello, vamos a empezar como bien ya ustedes saben, creando un test:

```dart
void main() {
  test(
      'Given a askForTable function, When executed with a N number of diners, Then it should return if has or not cappacity',
      () {
    // Given
    final diners = 5;

    // When
    final result = askForTable(diners);

    // Then
    expect(result, true);
  });
}
```

Tenemos nuestro test realizado según lo que vimos hasta ahora aunque imaginemos
un poco la situación:

1. Envío un pedido a esta aplicación.
2. Le llega al sistema y este debe chequear la cantidad de mesas ocupadas además
   de la lista de espera que puede tener en el mismo restaurant.

El segundo punto puede tomar algún tiempo por lo que no es una respuesta que
podamos tener en el momento. Por ello, nuestros tests van a tener que cambiar:

```dart
void main() {
  group('Given a group of diners', () {
    test('When there are more than 4 diners, Then askForTable returns false',
        () {
      expectLater(askForTable(5), completion(isFalse));
    });

    test(
        'When there are less than or equal to 4 diners, Then askForTable returns true',
        () {
      expectLater(askForTable(4), completion(isTrue));
    });
  });
}
```

En primer lugar, van a ver que las descripciones cambiaron un poco y lo
ordenamos en un grupo. Además de esto, tenemos métodos que no conocían:

### `expectLater`

El método `expectLater` en un test es similar al `expect`, pero además de
verificar el valor de la expresión que se está evaluando, también permite
trabajar con un flujo en donde tenemos demoras en el tiempo.

En el ejemplo, el `expectLater` se utiliza para verificar que el
valor que retorna la función `askForTable` sea igual a `true`
cuando se le pasa un número de comensales menor o igual a 4, y `false` en caso
contrario.

### `completion`

El `completion` es un argumento opcional que se puede pasar a la función
`expectLater` y sirve para especificar una función de _callback_ que se llamará
cuando el futuro asociado (nuestra función `askForTable`) se complete.

### callback

Un _callback_ es una función que se pasa como argumento a otra función y que será
llamada dentro de esa función en un momento específico o cuando se cumpla alguna
condición determinada. El propósito es especificar el comportamiento que se debe
ejecutar en una determinada situación.

Los _callbacks_ son muy comunes en programación asincrónica, donde se utilizan
para notificar al cliente que un proceso se ha completado o que se ha producido
un error. Por ejemplo, en nuestra caso, `isTrue` es el _callback_ que recibe
nuestro _matcher_ llamado `completion` y lo que va a hacer es comparar el
resultado de `askFormTable`.

Para todo lo anterior, necesitamos que nuestra función simule una demora y esto
va a agregar varias cosas que no conocemos:

```dart
// Ya no esperamos simplemente un bool, sino que esperamos un Future<bool>;
// es la forma de representar que la función va a devolver un valor en el futuro.
Future<bool> askForTable(int diners) {
  // Para hacerlo utilizamos Future.delayed que es una función que nos permite
  // crear un Future que se va a resolver en el tiempo que estipulemos.
  // En este caso, el Future se va a resolver en 3 segundos.
  // El segundo parámetro es una función que se va a ejecutar cuando el Future
  // se resuelva. Y es un callback que devuelve un bool.
  return Future.delayed(Duration(seconds: 3), () {
    if (diners > 4) {
      return false;
    } else {
      return true;
    }
  });
}
```

Si ejecutan el test van a poder observar que se toma su tiempo; de hecho pueden
subir la cantidad a 10 segundos para que así no les quede ninguna duda de que
existe una demora real.

Tenemos test, tenemos función... cómo la utilizamos? Así?

```dart
void main() {
  print('🚀 The process has started!');
  final result = askForTable(5);
  print(result);
}
```

### `then`

Como dijimos anteriormente, tendríamos que esperar que `askForTable` haga lo que
tenga que hacer y para ello los _futures_ cuentan con el método `then`:

```dart
void main() {
  print('🚀 The process has started!');
  // Para utilizar el Future, lo que hacemos es llamar a la función y
  // utilizar el método then. El método then recibe una función que se va a
  // ejecutar cuando el Future se resuelva.
  askForTable(5).then((value) => print(value));
}
```

Podríamos hacer algo un poco más _user friendly_ verdad?

```dart
void main() {
  print('🚀 The process has started!');
  // Para utilizar el Future, lo que hacemos es llamar a la función y
  // utilizar el método then. El método then recibe una función que se va a
  // ejecutar cuando el Future se resuelva.
  askForTable(5).then((value) {
    if (value == true) {
      print('You have a table! 🥳');
    } else {
      print('You don\'t have a table! 😋');
    }
  });
}
```

Si corremos nuestra aplicación veremos que demora 3 segundos y luego nos
arroja el resultado:

```shell
🚀 The process has started!
You don't have a table! 😋
Exited
```

Sin embargo, supongamos que podría pasar algo en el sistema
del restaurant y en lugar de respondernos exitosamente, nos envían un fallo.
Vamos a arrojar una `Exception` y de momento comentar el otro código:

```dart
Future<bool> askForTable(int diners) {
  return Future.delayed(Duration(seconds: 3), () {
    return throw Exception('We had a problem with the server');
    // if (diners > 4) {
    //   return false;
    // } else {
    //   return true;
    // }
  });
}
```

Si nosotros corriéramos la app ahora, veríamos una excepción a los tres segundos
de haberlo corrido verdad? Cómo podríamos manejar esa excepción?

### `catchError`

Para no interrumpir la ejecución de nuestro programa, utilizamos `catchError`
que es una función que recibe otro _callback_ a ser ejecutado si sucediera un error:

```dart
void main() {
  print('🚀 The process has started!');
  askForTable(5).then((value) {
    if (value == true) {
      print('You have a table! 🥳');
    } else {
      print('You don\'t have a table! 😋');
    }
    // El método catchError se ejecuta cuando se produce un error
  }).catchError((error) {
    print('Error: $error');
  });
}
```

Y si ahora corren la app, verán que nuestro error fue manejado gustozamente!

```shell
🚀 The process has started!
Error: Exception: We had a problem with the server
Exited
```

Y podríamos completar el proceso imprimiendo algo que indique que se ha
finalizado. Podríamos hacer algo simple:

```dart
void main() {
  print('🚀 The process has started!');
  askForTable(5).then((value) {
    if (value == true) {
      print('You have a table! 🥳');
    } else {
      print('You don\'t have a table! 😋');
    }
    // El método catchError se ejecuta cuando se produce un error
  }).catchError((error) {
    print('Error: $error');
  });
  print('The process has finished! 🤓');
}
```

Sin embargo cuando corren la aplicación van a ver que pareciera que el proceso
terminó antes de comenzar! 😒 Esto es debido a que el _future_ toma tres
segundos pero mientras la aplicación sigue:

```shell
🚀 The process has started!
The process has finished! 🤓
Error: Exception: We had a problem with the server
Exited
```

Para poder lograr lo que queremos, vamos a utilizar otro método más de los
_futures_.

### `whenComplete`

Nuevamente, otro método que recibe un _callback_ encargado de ejecutarse luego
de los métodos anteriores:

```dart
void main() {
  print('🚀 The process has started!');
  askForTable(5).then((value) {
    if (value == true) {
      print('You have a table! 🥳');
    } else {
      print('You don\'t have a table! 😋');
    }
    // El método catchError se ejecuta cuando se produce un error
  }).catchError((error) {
    print('Error: $error');
  }).whenComplete(() => print('The process has finished! 🤓'));
}

```

Eliminemos la excepción:

```dart
Future<bool> askForTable(int diners) {
  return Future.delayed(Duration(seconds: 3), () {
    if (diners > 4) {
      return false;
    } else {
      return true;
    }
  });
}
```

Y ahora sí, vamos a tener todo en orden:

```shell
🚀 The process has started!
You don't have a table! 😋
The process has finished! 🤓
Exited
```

Bien! Estamos empezando a manejar el tiempo en nuestras app aunque lo que vimos
en este capítulo es solo a modo de introducción, para que tomen consciencia de
cómo el tiempo transcurre en la ejecución ya que no es la forma óptima de tratar
con operaciones asíncronas. Para ello, vayan al próximo capítulo!
